{
    cover_title: 'Ereleden | LVSV Antwerpen',
    cover_subtitle: 'Providing essential liberty since 1947',
    $header_image_type: 'image',
    header_image: 'assets/img/openingsdebat.jpg',
    ereleden_title: 'Ereleden 2016-2017',
    ereleden_text: 'LVSV Antwerpen bedankt van harte haar ereleden',
    ereleden_left_column: [
        {name: 'Alexander De Croo'},
        {name: 'Alfons Borginon + Kristin'},
        {name: 'Annemie Neyts-(Uyttebroeck)'},
        {name: 'Annemie Turtelboom'},
        {name: 'Bart Lauryssen'},
        {name: 'Bart Somers (Miet Bourlon)'},
        {name: 'Bart Tommelein'},
        {name: 'Brigitta Dourcy-Belle-Rose'},
        {name: 'Caroline Leys'},
        {name: 'Christophe Wuyts'},
        {name: 'Claude Marinower '},
        {name: 'Dogan Pinar'},
        {name: 'Flor(ent) Keveryn'},
        {name: 'Guy Vanhengel'},
        {name: 'Gwendolyn Rutten'},
        {name: 'Hans Maes'},
        {name: 'Hendrik Daems'},
        {name: 'Herman De Croo'},
        {name: 'Jerry Van Echelpoel'},
    ],
    ereleden_right_column: [
        {name: 'Karel De Gucht'},
        {name: 'Kelly Sabbe'},
        {name: 'Koenraad Helsen'},
        {name: 'Kristof Droessaert'},
        {name: 'Lander Hannes'},
        {name: 'Ludo Van Campenhout'},
        {name: 'Markowitz-Markowitz'},
        {name: 'Martine Taelman'},
        {name: 'Mathias Adriaenssens'},
        {name: 'Michel Van Genechten'},
        {name: 'Paul Greant'},
        {name: 'Philippe De Backer'},
        {name: 'Stef Van Beek'},
        {name: 'Sven Gatz'},
        {name: 'Valerie Van Genechten'},
        {name: 'Van De Roye-De Decker R+ H'},
        {name: 'William Mostmans'},
        {name: 'Yolande Avontroodt'},
    ],
    pricing: 'Indien u erelid wil worden, kan u steeds 35 euro storten op het rekeningnummer BE64651147095452 met de vermelding erelid. Uw naam zal verschijnen op de website en op de presentatie tijdens onze debatten.',
    contact_title: 'Vind ons!',
    facbook_url: 'https://www.facebook.com/LVSV.Antwerpen/',
    twitter_url: 'https://twitter.com/LVSVAntwerpen',
    google_url: '',
    instagram_url: 'https://www.instagram.com/lvsv.antwerpen/',
    linkedin_url: 'https://www.linkedin.com/company/10833720',
    youtube_url: '',
    rss_url: '',
    email: 'voorzitter@lvsvantwerpen.be'
}
